apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  labels:
    app: jenkins
type: Opaque
data:
  JENKINS_ADMIN_ID: {{ .Values.controller.adminUser | b64enc | quote }}
  JENKINS_ADMIN_PASSWORD: {{ .Values.controller.adminPassword | b64enc | quote }}
